#!/usr/bin/env python3
import ipaddress
import sys

cidr = sys.argv[1]
network = ipaddress.IPv4Network(cidr, strict=False)
ip_list = [str(ip) for ip in network.hosts()]
for ip in ip_list:
    print(ip)
